version: '3.7'

services:
  elastic:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: "${REGISTRY_NAME}devclubiitd/elasticsearch:0.1"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200 # Need to expose for frontend
    networks:
      - "internal"
    restart: "unless-stopped"

  crawler:
    build: 
      context: ./Crawler
      dockerfile: Dockerfile
    # image: "${REGISTRY_NAME}devclubiitd/haystack_crawler:0.1"
    restart: "unless-stopped"
    networks:
      - "internal"
      - "reverseproxy"
    environment:
      - ELASTIC_URL=http://elastic:9200
    depends_on:
      - elastic

  react_app:
    build:
      context: ./search_frontend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - "internal"
    ports:
      - 3000:3000
    environment:
      - ELASTIC_URL= http://localhost:9200
    depends_on:
      - elastic

volumes:
  elastic_data:
    # driver: local #as it is running on local docker environment at the time of development

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:

