version: '3.7'

services:
  elastic:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: "${REGISTRY_NAME}devclubiitd/elasticsearch:0.1"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - "internal"
    restart: "unless-stopped"

  crawler:
    build: 
      context: ./Crawler
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - "internal"
      - "reverseproxy"
    depends_on:
      - elastic

  nginx:
    image: "${REGISTRY_NAME}devclubiitd/citadel-nginx:0.1"
    build: ./nginx
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 7000:80
    depends_on:
        - elastic
        - react_app
    networks:
      - "reverseproxy"
      - "internal"
    restart: always

  react_app:
    build:
      context: ./search_frontend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - "internal"
    depends_on:
      - elastic

volumes:
  elastic_data:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:

